package main

var t = `
// generated by discover
// DO NOT EDIT!!!
{{range .}}
func Get{{.}}WithId(id string) *grpc.ClientConn {
	return _default_pool.get_service_with_id(DEFAULT_SERVICE_PATH + "/{{.}}", id)
}
{{end}}

// get a service in round-robin style
// especially useful for load-balance with state-less services
{{range .}}
func Get{{.}}() *grpc.ClientConn {
	return _default_pool.get_service(DEFAULT_SERVICE_PATH + "/{{.}}")
}
{{end}}

// bind names
var known_names = make(map[string]bool)
func Init() {
	{{range .}}
	known_names[DEFAULT_SERVICE_PATH+"/{{.}}"] = true
	{{end}}
	_default_pool.init()
}
`
